// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"NewGameButtonOnly","status":true,"description":"This plugin shows only the new game button on the title screen","parameters":{}}
];
